CREATE TABLE IF NOT EXISTS users (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(100) UNIQUE NOT NULL,
  email varchar(150) UNIQUE NOT NULL,
  password_hash varchar(255) NOT NULL,
  role varchar(50) NOT NULL DEFAULT 'viewer',
  is_active boolean NOT NULL DEFAULT true,
  last_login_at timestamp,
  created_at timestamp NOT NULL DEFAULT NOW(),
  updated_at timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS batch_executions (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  started_at timestamp NOT NULL,
  finished_at timestamp,
  status varchar(50) NOT NULL,
  total_events_detected int NOT NULL DEFAULT 0,
  total_events_processed int NOT NULL DEFAULT 0,
  total_events_failed int NOT NULL DEFAULT 0,
  log_summary text,
  error_message text,
  created_at timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS events (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar(255) NOT NULL,
  manual_description text,
  generated_description text,
  event_date timestamp,
  country varchar(100),
  language varchar(50),
  status varchar(50) NOT NULL DEFAULT 'pending',
  created_by int NOT NULL,
  last_batch_execution_id int,
  processed_at timestamp,
  created_at timestamp NOT NULL DEFAULT NOW(),
  updated_at timestamp NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_events_created_by FOREIGN KEY (created_by) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT fk_events_last_batch FOREIGN KEY (last_batch_execution_id) REFERENCES batch_executions (id) DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE IF NOT EXISTS images (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id int NOT NULL,
  uploaded_by int,
  storage_path varchar(500) NOT NULL,
  filename varchar(255) NOT NULL,
  mime_type varchar(100) NOT NULL,
  caption varchar(255),
  width int,
  height int,
  hash varchar(255),
  created_at timestamp NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_images_event FOREIGN KEY (event_id) REFERENCES events (id) DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT fk_images_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users (id) DEFERRABLE INITIALLY IMMEDIATE
);
