apiVersion: v1
kind: Secret
metadata:
  name: tfm-app-secret
  namespace: tfm-app
type: Opaque
stringData:
  POSTGRES_USER: "REPLACE_ME"
  POSTGRES_PASSWORD: "REPLACE_ME"
  API_SECRET_KEY: "REPLACE_ME"
  DATABASE_URL_API: "REPLACE_ME"
  DATABASE_URL_SVC: "REPLACE_ME"
