apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  namespace: tfm-app
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::296368270177:role/tfm-app-api-irsa-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: svc
  namespace: tfm-app
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::296368270177:role/tfm-app-svc-irsa-role